service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2

functions:
  hello:
    handler: handler.lambda_handler
    events:
      - httpApi:
          path: /
          method: get
