service: aws-python-project

frameworkVersion: '3'

provider:
  region: ap-northeast-2
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: opensearch-test-kyy
          event: s3:ObjectCreated:*
