service: s3-lambda

frameworkVersion: '3'

provider:
  region: ap-northeast-2
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
        - "S3:*"
      Resource:
        - "*"

functions:
  hello:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: opensearch-backup-kyy
          event: s3:ObjectCreated:*
          existing: true
